version: '3'

services:
  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - C:\Projects\Experiments\COE\Api\cftapi:/teamcity_data
      - teamcity_data:/data/teamcity_server/datadir
    networks:
      - coe

  
  gateway:
    image: envoyproxy/envoy:dev
    ports:
      - "10000:10000"
      - "10001:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    
    networks:
      - coe

  microservice:
    container_name: microservice
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
    networks:
      - coe

# Остальные сервисы

networks:
  coe:
    driver: bridge

volumes:
  teamcity_data:
    driver: local