logging:
  level:
    root: INFO
    com.example.gateway: DEBUG

spring:
  main:
    banner-mode: off

  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authserver:8080/auth/realms/myrealm/protocol/openid-connect/certs
