services:
  apigateway:
    container_name: apigateway
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8081:80"
    environment:
      - MICROSERVICE=microservice

  microservice:
    container_name: microservice
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
