services:
  apigateway:
    container_name: apigateway
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8081:81"
    environment:
      - APIGATEWAY_PORT=81
      - MICROSERVICE_PORT=80

  microservice:
    container_name: microservice
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
