services:
  apigateway:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - BACKEND=microservice

  microservice:
    image: kennethreitz/httpbin

