services:
  apigateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  authserver:
    image: jboss/keycloak
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  resourceserver:
    image: kennethreitz/httpbin


volumes:
  keycloak_data:
