services:
  gateway:
    container_name: gateway
    image: gateway
    ports:
      - "80:8080"

  microservice:
    container_name: microservice
    image: kennethreitz/httpbin
    ports:
      - "8080:80"
