logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG

spring:
  main:
    banner-mode: off

  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://authserver:8080/auth/realms/myrealm
          jwk-set-uri: http://authserver:8080/auth/realms/myrealm/protocol/openid-connect/certs

  cloud:
    gateway:
      default-filters:
        - DebugAccessToken
