services:
  envoyproxy:
    image: envoyproxy/envoy:dev-d3464bfd6d247530e669688c79e99c7245299df7
    ports:
      - "80:10000"
      - "81:9902"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml

  authserver:
    image: jboss/keycloak
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  resourceserver:
    image: kennethreitz/httpbin
    ports:
      - "8082:80"


volumes:
  keycloak_data:
