logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

spring:
  main:
    banner-mode: off

  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${auth.server}/auth/realms/myrealm/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: default
          uri: http://${resource.server}
          predicates:
            - Path=/**
