services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      - SPRING_MAIN_BANNER-MODE=OFF
      - SPRING_APPLICATION_NAME=api-gateway
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://auth-server:8080/auth/realms/myrealm/protocol/openid-connect/certs
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8080
      - SPRING_CONFIG_ACTIVATE_ON-PROFILE=master
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY=INFO
      - LOGGING_LEVEL_COM_EXAMPLE_GATEWAY=DEBUG
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tracing-server:9411/api/v2/spans
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0

  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    ports:
      - 81:8080
    environment:
      - SPRING_MAIN_BANNER-MODE=OFF
      - SPRING_APPLICATION_NAME=config-server
      - LOGGING_LEVEL_ROOT=INFO
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=http://git-server:3000/myuser/config-server.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=myuser
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=mypassword
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL=master
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH-PATHS={application}

  auth-server:
    image: jboss/keycloak
    ports:
      - 8081:8080
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  resource-server:
    image: kennethreitz/httpbin
    ports:
      - 8082:80

  tracing-server:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  git-server:
    image: gitea/gitea:latest
    ports:
      - 3000:3000
    volumes:
      - gitea_data:/data
      - gitea_data:/app/gitea/custom


volumes:
  keycloak_data:
  gitea_data:
