version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "80:81"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./jwt_handler.js:/etc/nginx/handlers/jwt_handler.js


  microservice:
    container_name: microservice
    image: kennethreitz/httpbin
    ports:
      - "8080:80"

  keycloak:
    image: jboss/keycloak
    ports:
      - "8180:8080"
    environment:
      DB_VENDOR: H2
